<?php

// ----- API de paypal -----
define('CLIENT_ID', 'AZPGXAEFcPRSHidHeDpKxinr5THwSIrBZ-Oj8vfA_RaKU4ZTO-lBQzYKMYXOb6lW48ZBK0PF_lDpnLyl');

// $CLIENT_ID = "AZPGXAEFcPRSHidHeDpKxinr5THwSIrBZ-Oj8vfA_RaKU4ZTO-lBQzYKMYXOb6lW48ZBK0PF_lDpnLyl";
